### ISSUE TITLE
Support all images and gifs in docs articles 

### ISSUE THREAD

**Issue by Konstantynova** [nboldhq/docs#2]
As of today, there are some images and gifs that are downloaded in docs admin but are not shown on the public page. 
The list of articles with described issue:
[[Update App Packages | documentation (nbold.co)](https://docs.nbold.co/quickstart/update-app-packages.html#how-to-update-the-nbold-app-packages)](url)
[[Allow nBold App and assign the right Teams Permission Policies | documentation](https://docs.nbold.co/quickstart/allow-nbold-app-and-assign-the-right-teams-permission-policies.html)](url) (last images missing)
[[Administrator Guide | documentation (nbold.co)](https://docs.nbold.co/quickstart/administrator-guide.html#create-a-collaboration-template)](url)
[[Serve Private Channels in Microsoft Teams only through Collaboration Templates | documentation (nbold.co)](https://docs.nbold.co/governance-policies/serve-private-channels.html#disable-the-ability-for-users-to-create-private-channel)](url)
[[Delegate your template catalog administration | documentation (nbold.co)](https://docs.nbold.co/quickstart/delegate-template-catalog-administration.html)](url) (1st image)
[[Files cloning for Collaboration Templates | documentation (nbold.co)](https://docs.nbold.co/collaboration-templates/files-and-folders.html#how-to-make-it-work)](url) (gif)
[[Adopt Microsoft Forms at scale through Collaboration Templates! | documentation (nbold.co)](https://docs.nbold.co/collaboration-templates/microsoft-forms.html)](url)
[[Full fidelity Planner cloning in Microsoft Teams | documentation (nbold.co)](https://docs.nbold.co/collaboration-templates/microsoft-planner.html)](url)
[[Office Documents and PDF Tabs in Microsoft Teams Template | documentation (nbold.co)](https://docs.nbold.co/collaboration-templates/office-and-pdf-documents.html)](url)
[[Private Channels in Collaboration Templates by nBold | documentation](https://docs.nbold.co/collaboration-templates/private-channels.html#_2-how-to-set-up)](url)
[[SharePoint Library Tab in Collaboration Templates | documentation (nbold.co)](https://docs.nbold.co/collaboration-templates/sharepoint-library.html)](url)
[[Wiki Tabs | documentation (nbold.co)](https://docs.nbold.co/collaboration-templates/wiki-tabs.html)](url)
[[Sensitivity Labels | documentation (nbold.co)](https://docs.nbold.co/governance-policies/sensitivity-labels.html#how-to-apply-them)](url)
[[Restrict guest access | documentation (nbold.co)](https://docs.nbold.co/governance-policies/restrict-guest-access.html#how-to-restrict-guest-access-to-teams-at-a-template-level)](url)
[[Permanent Owners and Members Policy | documentation (nbold.co)](https://docs.nbold.co/governance-policies/permanent-owners-and-members-policy.html)](url)
[[Security Policy | documentation (nbold.co)](https://docs.nbold.co/governance-policies/security-policy.html)](url)

**Comment by guillaumemeyer** [comment]
Should be fixed for most of these pages.
Please advise @Konstantynova
